const en = {
  "nav-tshirt": "T-shirts",
  "nav-giftbox": "Giftboxes",
  "nav-contacts": "Contacts",
  "support-btn": "Thank and support",
  "main-title": "Thank and Support the Ukrainian Army!",
  "shirt-desc1":
    "We have designed exclusive T-shirts with an embroidered camouflage heart so that everyone can show their gratitude and respect to Ukrainian Defenders just by putting the T-shirt on for a walk in the city.",
  desc2:
    "100% of income will be used to purchase DJI Mavic Fly More Combo and DJI RC Pro drones for A special detachment of the National Guard of Ukraine «Vega» and the 10th separate mountain assault brigade, artillery division.",
  "how-to-get-heading": "How to get a T-shirt?",
  step1: "Step 1:",
  step2: "Step 2:",
  step3: "Step 3:",
  step4: "Step 4:",
  "step1-text": "Fill in the form.",
  "fill-form-btn": "To fill in the form",
  "step2-text": "Make a donation of over 700 UAH to a Monobank account.",
  "step3-text": "Send a screenshot of your successful transaction to the organizers",
  "step4-text": "Once your T-shirt is ready, we'll mail it to you.",
  organizers: "The Org Team",
  "contact-us": "Happy to answer any questions you have",
  valery: "Valery",
  vlad: "Vlad",
  orysia: "Orysia",
  partners: "Our partners",
  "golka-desc": "Embroidery services for business",
  "hygge-desc": "A brand of basic clothing",
  "oksana-lomaha": "Oksana Lomaha",
  "lamaha-desc": "Photographer, designer",
  "bohdan-manchur": "Bogdan Manchur",
  "manchur-desc": "Videographer",
  "giftbox-for-donate": "Giftbox for donate",
  giftbox: "Giftbox",
  "giftbox-desc":
    "For special occasions we’ve created a special gift set. By purchasing it you will not only please your loved ones, but you will also support the Armed Forces of Ukraine, speeding up our Victory!",
  "giftbox-items": "What's in there:",
  tshirt: "Embroidered T-shirt",
  flag: "Ukrainian Flag",
  postmarks: "Postmarks",
  cup: "A branded mug",
  toy: "Handmade toy",
  gingerbread: "Fortune Gingerbread cookies",
  chocolate: "Chocolate",
  "get-giftbox-heading": "How to get a giftbox?",
  "giftbox-step1": " Make a donation of over 1500 UAH to a Monobank account.",
  "giftbox-step2":
    "Send a screenshot of your successful transaction to the organizers, so we could get in touch with you.",
  "giftbox-step3": "Once your giftbox is ready, we'll mail it to you.",

  "nav-hoodie": "Hoodies",
  hoodies: "Hoodies",
  "get-hoodie-heading": "How to get a Hoodie?",
  "hoodie-desc":
    "In summer we wore T-shirts with grateful camouflage hearts, and now that autumn has come let’s get warmer wearing cozy hoodies embroidered with your gratitude to our Defenders.",
  "hoodie-step1": "Fill in the form.",
  "hoodie-step2": "Make a donation of over 1300 UAH to a Monobank account.",
  "hoodie-step3": "Send a screenshot of your successful transaction to the organizers",
  "hoodie-step4": "Once your hoodie is ready, we'll mail it to you.",
};

export default en;
